-- ============================================================
-- Commerce Sales & Customer Analysis
-- SQL / MySQL
-- ============================================================
--
-- Project Objective:
-- Analyze customer behavior, product performance, sales trends,
-- and revenue using SQL to generate business insights.
--
-- Database: EcommerceDB
-- Tool: MySQL Workbench
-- ============================================================

CREATE DATABASE EcommerceDB;
USE EcommerceDB;
SHOW TABLES;
SELECT 'Customers' AS table_name, COUNT(*) AS row_count FROM customers
UNION ALL
SELECT 'Products',COUNT(*) FROM products
UNION ALL
SELECT 'Orders',COUNT(*) FROM orders 
UNION ALL
SELECT 'OrderDetails',COUNT(*) FROM orderdetails;

-- Checking for Duplicates
SELECT customer_id,COUNT(*) FROM customers GROUP BY customer_id HAVING COUNT(*)>1;
SELECT product_id,COUNT(*) FROM products GROUP BY product_id HAVING COUNT(*)>1;
SELECT order_id,COUNT(*) FROM orders GROUP BY order_id HAVING COUNT(*)>1;
SELECT order_id,product_id,COUNT(*) FROM orderdetails GROUP BY order_id,product_id HAVING COUNT(*)>1;
SELECT * FROM orderdetails WHERE order_id=3 AND product_id=7;

-- Checking for Missing values
SELECT SUM(customer_id IS NULL) AS missing_id, SUM(name IS NULL) AS missing_name, SUM(location IS NULL) AS missing_loc FROM Customers;
SELECT SUM(product_id IS NULL) AS missing_id,SUM(name IS NULL) AS missing_name,SUM(category IS NULL) AS missing_category,SUM(price IS NULL) AS missing_price FROM Products; 
SELECT SUM(order_id IS NULL) AS missing_id, SUM(order_date IS NULL) AS missing_date,SUM(customer_id IS NULL) AS missing_customer_id,SUM(total_amount IS NULL) AS missing_total_amount FROM Orders;
SELECT SUM(order_id IS NULL) AS missing_order_id,SUM(product_id IS NULL) AS missing_product_id,SUM(quantity IS NULL) AS missing_quantity,SUM(price_per_unit IS NULL) AS missing_price_per_unit FROM OrderDetails;

SELECT o.order_id,o.total_amount AS order_total,SUM(od.quantity * od.price_per_unit) AS total
FROM orders o JOIN orderdetails od ON o.order_id = od.order_id 
GROUP BY o.order_id,o.total_amount ORDER BY o.order_id;

-- checking foreign key consistency
SELECT o.customer_id FROM orders o LEFT JOIN customers c ON o.customer_id = c.customer_id WHERE c.customer_id IS NULL;
SELECT od.order_id FROM orderdetails od LEFT JOIN orders o ON od.order_id = o.order_id WHERE o.order_id IS NULL;
SELECT od.product_id FROM orderdetails od LEFT JOIN products p ON od.product_id = p.product_id WHERE p.product_id IS NULL;

-- Total Revenue generated by the Company
SELECT SUM(total_amount) AS total_revenue FROM orders;
-- total no.of orders and average order value
SELECT COUNT(order_id) AS no_of_orders, AVG(total_amount) AS avg_order_value FROM orders;

-- Customer Insights

SELECT COUNT(DISTINCT customer_id) AS cust_with_orders FROM orders;
SELECT c.customer_id,c.name,c.location,SUM(o.total_amount) AS total_orders 
FROM customers c JOIN orders o ON c.customer_id = o.customer_id 
GROUP BY c.customer_id,c.name,c.location ORDER BY SUM(o.total_amount) DESC LIMIT 10;
-- Repeat Customers
SELECT COUNT(DISTINCT customer_id) AS cust_with_orders,
COUNT(DISTINCT CASE WHEN order_count>1 THEN customer_id END) AS repeat_customers FROM
(SELECT customer_id,COUNT(order_id) AS order_count FROM orders GROUP BY customer_id) AS customer_orders;
-- Average Spending per Customer
SELECT c.customer_id, c.name, COUNT(o.order_id) AS order_count, SUM(o.total_amount) AS total_spent,
AVG(o.total_amount) AS avg_order_value FROM customers c JOIN orders o ON c.customer_id = o.customer_id 
GROUP BY c.customer_id,c.name ORDER BY total_spent DESC;

-- Product Analysis

-- Product with highest Revenue
SELECT p.product_id, p.name, p.category, SUM(od.quantity * od.price_per_unit) AS product_revenue,
SUM(od.quantity) AS units_sold FROM products p JOIN orderdetails od ON p.product_id = od.product_id
GROUP BY p.product_id,p.name,p.category ORDER BY product_revenue DESC;
-- Revenue By Category
SELECT p.category, SUM(od.quantity * od.price_per_unit) AS category_revenue, SUM(od.quantity) AS units_sold
FROM products p JOIN orderdetails od ON p.product_id = od.product_id 
GROUP BY p.category ORDER BY category_revenue DESC;
-- Lowest Selling Products
SELECT p.product_id,p.name,p.category,SUM(od.quantity * od.price_per_unit) AS product_revenue,SUM(od.quantity) AS units_sold
FROM products p JOIN orderdetails od ON p.product_id = od.product_id 
GROUP BY p.product_id,p.name,p.category ORDER BY product_revenue ASC LIMIT 3;
-- Average Selling price by Category
SELECT p.category, AVG(od.price_per_unit) AS avg_selling_price FROM products p JOIN orderdetails od 
ON p.product_id = od.product_id GROUP BY p.category ORDER BY avg_selling_price DESC;

-- Monthly Sales Analysis

-- Orders per month 
SELECT MONTH(STR_TO_DATE(order_date,'%d-%m-%Y')) AS order_month,COUNT(order_id) AS total_orders FROM Orders
GROUP BY MONTH(STR_TO_DATE(order_date,'%d-%m-%Y')) ORDER BY order_month;
-- Monthly Revenue
SELECT MONTH(STR_TO_DATE(order_date,'%d-%m-%Y')) AS order_month,SUM(total_amount) AS revenue FROM orders
GROUP BY MONTH(STR_TO_DATE(order_date,'%d-%m-%Y')) ORDER BY order_month;
-- Highest Revenue Months
SELECT MONTH(STR_TO_DATE(order_date,'%d-%m-%Y')) AS order_month,SUM(total_amount) AS monthly_revenue FROM orders
GROUP BY MONTH(STR_TO_DATE(order_date,'%d-%m-%Y')) ORDER BY monthly_revenue DESC LIMIT 3;

-- Advanced Analysis

-- Rank Customers by total spending
SELECT c.customer_id,c.name,SUM(o.total_amount) AS total_spent, RANK() OVER(ORDER BY SUM(o.total_amount) DESC) AS rnk
FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id,c.name ORDER BY rnk;
-- Customer Contribution to Total Revenue
WITH customer_revenue AS(
SELECT c.customer_id,c.name,SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id,c.name)
SELECT customer_id,name,total_spent,ROUND(total_spent*100.0/SUM(total_spent) OVER(),2) AS revenue_contribution_pct FROM customer_revenue ORDER BY total_spent DESC;
-- Customers spending above the average
WITH customer_spending AS(
SELECT c.customer_id,c.name,SUM(o.total_amount) AS total_spent FROM customers c JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.customer_id, c.name)
SELECT customer_id,name,total_spent FROM customer_spending
WHERE total_spent > (SELECT AVG(total_spent) FROM customer_spending) ORDER BY total_spent DESC;
-- Product Ranking within each category
WITH  product_revenue AS(
SELECT p.product_id,p.name,p.category,SUM(od.quantity*od.price_per_unit) AS product_revenue 
FROM products p JOIN orderdetails od ON p.product_id = od.product_id GROUP BY p.product_id,p.name,p.category)
SELECT product_id,name,category,product_revenue,RANK() OVER(PARTITION BY category ORDER BY product_revenue DESC) AS category_rank
FROM product_revenue ORDER BY category,category_rank;
-- Sales Volume vs Revenue Performance
SELECT p.product_id, p.name, p.category, SUM(od.quantity) AS units_sold, SUM(od.quantity * od.price_per_unit) AS product_revenue
FROM products p JOIN orderdetails od ON p.product_id = od.product_id 
GROUP BY p.product_id,p.name,p.category ORDER BY product_revenue DESC;

-- ============================================================
-- PROJECT SUMMARY
-- ============================================================

-- Key Business Findings:
-- 1. Total company revenue: ₹19,783,000
-- 2. Total orders: 200
-- 3. Average order value: ₹98,915
-- 4. 84 customers placed at least one order.
-- 5. 58 of the 84 ordering customers were repeat customers.
-- 6. Laptop 15" Pro generated the highest product revenue.
-- 7. Digital SLR Camera recorded the highest units sold.
-- 8. Electronics generated the highest category revenue.
-- 9. September generated the highest monthly revenue.
-- 10. Product ranking was performed within categories using
--     RANK() and PARTITION BY.
